spring:
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost/pedidocerto}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:postgres}
        hikari:
            maximum-pool-size: 30
            minimum-idle: 20
            idle-timeout: 10000
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: true
    flyway:
        locations: classpath:db/migration,classpath:db/datatest
    messages:
        basename: messages
        fallback-to-system-locale: false
